var Snooper = require('reddit-snooper');
snooper = new Snooper({
  automatic_retries: true,
  api_requests_per_minuite: 5
});

console.log('listening..');
snooper.watcher.getPostWatcher('gaming')
  .on('post', function(post) {
    console.log(post)
  })
  .on('error', console.error)

// post object example
// { kind: 't3',
//   data:
//    { domain: 'i.redd.it',
//      approved_at_utc: null,
//      banned_by: null,
//      media_embed: {},
//      thumbnail_width: 140,
//      subreddit: 'gaming',
//      selftext_html: null,
//      selftext: '',
//      likes: null,
//      suggested_sort: null,
//      user_reports: [],
//      secure_media: null,
//      is_reddit_media_domain: true,
//      link_flair_text: null,
//      id: '75bmk3',
//      banned_at_utc: null,
//      view_count: null,
//      archived: false,
//      clicked: false,
//      report_reasons: null,
//      title: 'When you gotta finish the quest before work',
//      num_crossposts: 0,
//      saved: false,
//      mod_reports: [],
//      can_mod_post: false,
//      is_crosspostable: false,
//      pinned: false,
//      score: 1,
//      approved_by: null,
//      over_18: false,
//      hidden: false,
//      preview: { images: [Object], enabled: true },
//      thumbnail: 'https://b.thumbs.redditmedia.com/u3EXC-iRx4Ic-mruDMQBWHakSx6Cl_lBBR1IiSFbs2Q.jpg',
//      subreddit_id: 't5_2qh03',
//      edited: false,
//      link_flair_css_class: null,
//      author_flair_css_class: null,
//      contest_mode: false,
//      gilded: 0,
//      downs: 0,
//      brand_safe: true,
//      secure_media_embed: {},
//      removal_reason: null,
//      post_hint: 'image',
//      author_flair_text: null,
//      stickied: false,
//      can_gild: false,
//      thumbnail_height: 140,
//      parent_whitelist_status: 'all_ads',
//      name: 't3_75bmk3',
//      spoiler: false,
//      permalink: '/r/gaming/comments/75bmk3/when_you_gotta_finish_the_quest_before_work/',
//      subreddit_type: 'public',
//      locked: false,
//      hide_score: true,
//      created: 1507607061,
//      url: 'https://i.redd.it/sgrum3boyuqz.jpg',
//      whitelist_status: 'all_ads',
//      quarantine: false,
//      author: 'MoeOnMeth',
//      created_utc: 1507578261,
//      subreddit_name_prefixed: 'r/gaming',
//      ups: 1,
//      media: null,
//      num_comments: 0,
//      is_self: false,
//      visited: false,
//      num_reports: null,
//      is_video: false,
//      distinguished: null } }
